# Generated by Django 6.0.4 on 2026-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'Kullanıcı'), ('admin', 'Belediye Çalışanı'), ('system_admin', 'Sistem Yöneticisi')], default='user', max_length=12, verbose_name='Kullanıcı Türü'),
        ),
    ]
