# Generated by Django 6.0.2 on 2026-02-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Şikayet Başlığı')),
                ('description', models.TextField(verbose_name='Şikayet Açıklaması')),
                ('category', models.CharField(choices=[('infrastructure', 'Altyapı'), ('traffic', 'Trafik'), ('pothole', 'Çukur'), ('water', 'Su Kaçağı'), ('trash', 'Çöp'), ('other', 'Diğer')], max_length=100, verbose_name='Kategori')),
                ('city', models.CharField(max_length=100, verbose_name='İl')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='Adres')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=20, verbose_name='Öncelik Seviyesi')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('rejected', 'Reddedildi')], default='new', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şikayet',
                'verbose_name_plural': 'Şikayetler',
                'ordering': ['-created_at'],
            },
        ),
    ]
