# Generated by Django 6.0.4 on 2026-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('security', 'Güvenlik ve İstismar'), ('infrastructure', 'Yapı ve Altyapı'), ('water', 'Su ve Kanalizasyon'), ('environment', 'Çevre ve Temizlik'), ('traffic', 'Ulaşım ve Trafik'), ('public_order', 'Zabıta ve Kamu Düzeni'), ('veterinary', 'Veterinerlik'), ('other', 'Genel / Diğer')], max_length=100, verbose_name='Kategori'),
        ),
    ]
