# Generated by Django 6.0.4 on 2026-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_update_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='llm_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='LLM Güven Skoru'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='llm_needs_review',
            field=models.BooleanField(blank=True, null=True, verbose_name='İnsan Onayı Gerekli'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='llm_reasoning',
            field=models.TextField(blank=True, default='', verbose_name='LLM Muhakemesi'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='llm_summary',
            field=models.TextField(blank=True, default='', verbose_name='LLM Özeti'),
        ),
    ]
